version: '3.7'

services:
  api:
    build: .
    container_name: javapro_api
    profiles:
      - test
    restart: unless-stopped
    ports:
      - "8444:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    networks:
      - lan
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    container_name: javapro_postgres
    restart: always
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=javapro"
    ports:
      - "5444:5432"
    volumes:
      - postgres_dev:/var/lib/postgresql/data
      - ./sql:/sql
    networks:
      - lan

networks:
  lan:
    driver: bridge

volumes:
  postgres_dev: